//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitzar.PagFun {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitzar.PagFun.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro Motivo Cancelamento não encontrado, verifique..
        /// </summary>
        public static string CancellationReasonNotFound {
            get {
                return ResourceManager.GetString("CancellationReasonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;ChargeFee&apos; não enviado no request..
        /// </summary>
        public static string ChargeFeeNotFound {
            get {
                return ResourceManager.GetString("ChargeFeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Comando não encontrado..
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existente um cadastro com este CPF..
        /// </summary>
        public static string CPFExists {
            get {
                return ResourceManager.GetString("CPFExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;DebitValue&apos; não enviado no request..
        /// </summary>
        public static string DebitValueNotFound {
            get {
                return ResourceManager.GetString("DebitValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível encontrar um estabelecimento vinculado ao usuário..
        /// </summary>
        public static string IdEstablishmentParentNotFound {
            get {
                return ResourceManager.GetString("IdEstablishmentParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &quot;IdEvent&quot; não enviado no request..
        /// </summary>
        public static string IdEventNotFound {
            get {
                return ResourceManager.GetString("IdEventNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro IdOrder não encontrado, verifique..
        /// </summary>
        public static string IdOrderNotFound {
            get {
                return ResourceManager.GetString("IdOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;IdParent&apos; não enviado no request..
        /// </summary>
        public static string IdParentNotFound {
            get {
                return ResourceManager.GetString("IdParentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto não encontrado..
        /// </summary>
        public static string IdProductNotFound {
            get {
                return ResourceManager.GetString("IdProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;IdUser&apos; não enviado no request..
        /// </summary>
        public static string IdUserNotFound {
            get {
                return ResourceManager.GetString("IdUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor de crédito inserido não corresponde com o saldo atual..
        /// </summary>
        public static string InvalidCreditValue {
            get {
                return ResourceManager.GetString("InvalidCreditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;Lang&apos; não enviado no request..
        /// </summary>
        public static string LangNotFound {
            get {
                return ResourceManager.GetString("LangNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parâmetro do link gerado não encontrado..
        /// </summary>
        public static string LinkNotFound {
            get {
                return ResourceManager.GetString("LinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação não autorizada..
        /// </summary>
        public static string NotAuthorizedOperation {
            get {
                return ResourceManager.GetString("NotAuthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;OperationDetail&apos; não enviado no request..
        /// </summary>
        public static string OperationDetailNotFound {
            get {
                return ResourceManager.GetString("OperationDetailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &quot;PromoterEmail&quot; não enviado no request..
        /// </summary>
        public static string PromoterEmailNotFound {
            get {
                return ResourceManager.GetString("PromoterEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &quot;PromoterName&quot; não enviado no request..
        /// </summary>
        public static string PromoterNameNotFound {
            get {
                return ResourceManager.GetString("PromoterNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parâmetro da quantidade não encontrado..
        /// </summary>
        public static string QuantidadeNotFound {
            get {
                return ResourceManager.GetString("QuantidadeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parâmetro &quot;Repositorio&quot; não enviado no request..
        /// </summary>
        public static string RepositoryNotFound {
            get {
                return ResourceManager.GetString("RepositoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chamada de categorias com problema ou sem retorno..
        /// </summary>
        public static string RequestCategoriesFail {
            get {
                return ResourceManager.GetString("RequestCategoriesFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não encontrado o parametro .
        /// </summary>
        public static string RequestTransferTicketFail {
            get {
                return ResourceManager.GetString("RequestTransferTicketFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &quot;Search&quot; não enviado no request..
        /// </summary>
        public static string RequestUsersFail {
            get {
                return ResourceManager.GetString("RequestUsersFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O validador não foi informado ou a informação não está válida..
        /// </summary>
        public static string RequestValidatorNotFoundOrInvalid {
            get {
                return ResourceManager.GetString("RequestValidatorNotFoundOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;SiteTax&apos; não enviado no request..
        /// </summary>
        public static string SiteTaxNotFound {
            get {
                return ResourceManager.GetString("SiteTaxNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro SKU não encontrado, verifique..
        /// </summary>
        public static string SKUNotFound {
            get {
                return ResourceManager.GetString("SKUNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro &apos;QtdIngressos&apos; não enviado no request..
        /// </summary>
        public static string TickesQuantityNotFound {
            get {
                return ResourceManager.GetString("TickesQuantityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transferência não autorizada..
        /// </summary>
        public static string TransferNotAutorized {
            get {
                return ResourceManager.GetString("TransferNotAutorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parâmetro &quot;Type&quot; não enviado no request..
        /// </summary>
        public static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usúario não encontrado para realizar transferência do ticket..
        /// </summary>
        public static string UnknowUserTransfer {
            get {
                return ResourceManager.GetString("UnknowUserTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Datas para atualização não informadas..
        /// </summary>
        public static string UpdateDatesNotFound {
            get {
                return ResourceManager.GetString("UpdateDatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parametro não encontrado, verifique..
        /// </summary>
        public static string UpdatePromoterEventsParamNotFound {
            get {
                return ResourceManager.GetString("UpdatePromoterEventsParamNotFound", resourceCulture);
            }
        }
    }
}
