//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitzar.Tickets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitzar.Tickets.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando não identificado para processamento..
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código de identificação do evento não é válido.
        /// </summary>
        public static string EventInvalidId {
            get {
                return ResourceManager.GetString("EventInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo ticket deve conter o código da sessão do evento.
        /// </summary>
        public static string NewTicketSectionInvalid {
            get {
                return ResourceManager.GetString("NewTicketSectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um ticket não pode ser criado com esse status.
        /// </summary>
        public static string NewTicketStatusInvalid {
            get {
                return ResourceManager.GetString("NewTicketStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação não autorizada..
        /// </summary>
        public static string NotAuthorizedOperation {
            get {
                return ResourceManager.GetString("NotAuthorizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da ordem de pagamento não é válido.
        /// </summary>
        public static string OrderInvalidId {
            get {
                return ResourceManager.GetString("OrderInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ticket foi encontrado com o código de ordem de pagamento informado.
        /// </summary>
        public static string OrderTicketsNotFound {
            get {
                return ResourceManager.GetString("OrderTicketsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parâmetros obrigatórios necessários não foram enviados com a solicitação.
        /// </summary>
        public static string ParametersNotFound {
            get {
                return ResourceManager.GetString("ParametersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O código de identificação da sessão não é válido.
        /// </summary>
        public static string SectionInvalidId {
            get {
                return ResourceManager.GetString("SectionInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do ticket inválido.
        /// </summary>
        public static string TicketInvalidId {
            get {
                return ResourceManager.GetString("TicketInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do dono do ticket não pode ser vazio.
        /// </summary>
        public static string TicketInvalidOwnerName {
            get {
                return ResourceManager.GetString("TicketInvalidOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ticket está em um status inválido para esta operação.
        /// </summary>
        public static string TicketInvalidStatus {
            get {
                return ResourceManager.GetString("TicketInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ticket foi encontrado.
        /// </summary>
        public static string TicketNotFound {
            get {
                return ResourceManager.GetString("TicketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O objeto enviado como ticket está inválido.
        /// </summary>
        public static string TicketObjectInvalid {
            get {
                return ResourceManager.GetString("TicketObjectInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de tikect inválido..
        /// </summary>
        public static string TypeInvalid {
            get {
                return ResourceManager.GetString("TypeInvalid", resourceCulture);
            }
        }
    }
}
