//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitzar.Products.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitzar.Products.Helper.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE btz_product ADD `UpdatedAt` TIMESTAMP;
        ///ALTER TABLE btz_product ADD `CreatedAt` TIMESTAMP;.
        /// </summary>
        internal static string AlterTable_AddUpdatedAndCreatedAt {
            get {
                return ResourceManager.GetString("AlterTable_AddUpdatedAndCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE btz_category ADD `Highlighted` BOOLEAN NOT NULL DEFAULT 0;.
        /// </summary>
        internal static string AlterTable_Category_Field_Highlighted {
            get {
                return ResourceManager.GetString("AlterTable_Category_Field_Highlighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE btz_product CHANGE `Updated_At` `UpdatedAt` TIMESTAMP;
        ///ALTER TABLE btz_product CHANGE `Created_At` `CreatedAt` TIMESTAMP;.
        /// </summary>
        internal static string AlterTable_RenameUpdatedAndCreatedAt {
            get {
                return ResourceManager.GetString("AlterTable_RenameUpdatedAndCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM btz_attributetypevalues WHERE Id = @p0 AND IdLanguage = @p1.
        /// </summary>
        internal static string Check_AttributeTypeValues {
            get {
                return ResourceManager.GetString("Check_AttributeTypeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM btz_attributevalues WHERE Id = @p0 AND IdLanguage = @p1;.
        /// </summary>
        internal static string Check_AttributeValues {
            get {
                return ResourceManager.GetString("Check_AttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM btz_categoryvalue WHERE IdCategory = @p0 AND IdLanguage = @p1.
        /// </summary>
        internal static string Check_CategoryValue {
            get {
                return ResourceManager.GetString("Check_CategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productfield (IdFieldGroup, Name, Type, ReadOnly) 
        ///SELECT * FROM (SELECT 1, &apos;Description&apos;, &apos;text&apos;, 0) T 
        ///WHERE NOT EXISTS (SELECT IdFieldGroup, Name, Type FROM btz_productfield WHERE Name = &apos;Description&apos;).
        /// </summary>
        internal static string CreateField_Description {
            get {
                return ResourceManager.GetString("CreateField_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productfield (IdFieldGroup, Name, Type, ReadOnly) 
        ///SELECT * FROM (SELECT 1, &apos;Gallery&apos; AS Name, &apos;gallery&apos; AS Type, 0) T 
        ///WHERE NOT EXISTS (SELECT IdFieldGroup, Name, Type FROM btz_productfield WHERE Name = &apos;Gallery&apos;).
        /// </summary>
        internal static string CreateField_Gallery {
            get {
                return ResourceManager.GetString("CreateField_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productfield (IdFieldGroup, Name, Type, ReadOnly) 
        ///SELECT * FROM (SELECT 1, &apos;Text&apos;, &apos;html&apos;, 0) T 
        ///WHERE NOT EXISTS (SELECT IdFieldGroup, Name, Type FROM btz_productfield WHERE Name = &apos;Text&apos;).
        /// </summary>
        internal static string CreateField_Text {
            get {
                return ResourceManager.GetString("CreateField_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productfield (IdFieldGroup, Name, Type, ReadOnly) 
        ///SELECT * FROM (SELECT 1, &apos;Url&apos;, &apos;text&apos;, 0) T 
        ///WHERE NOT EXISTS (SELECT IdFieldGroup, Name, Type FROM btz_productfield WHERE Name = &apos;Url&apos;).
        /// </summary>
        internal static string CreateField_Url {
            get {
                return ResourceManager.GetString("CreateField_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productfieldgroup (Description) 
        ///SELECT * FROM (SELECT &apos;Básico&apos;) T 
        ///WHERE NOT EXISTS (SELECT * FROM btz_productfieldgroup WHERE Description = &apos;Básico&apos;).
        /// </summary>
        internal static string CreateGroup_Basic {
            get {
                return ResourceManager.GetString("CreateGroup_Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_attribute
        ///(
        ///    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///    IdType INT,
        ///    Icon VARCHAR(999),
        ///    IdParent INT,
        ///    FOREIGN KEY (IdType) REFERENCES btz_attributetype(Id)
        ///).
        /// </summary>
        internal static string CreateTable_Attribute {
            get {
                return ResourceManager.GetString("CreateTable_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_attributetype
        ///(
        ///    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///    Codigo varchar(255)
        ///).
        /// </summary>
        internal static string CreateTable_AttributeType {
            get {
                return ResourceManager.GetString("CreateTable_AttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_attributetypevalues
        ///(
        ///    Id INT NOT NULL REFERENCES btz_attribute(Id),
        ///    IdLanguage INT NOT NULL,
        ///    Value VARCHAR(100) NOT NULL,
        ///    PRIMARY KEY 
        ///    (
        ///		Id,
        ///        IdLanguage
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_AttributeTypeValues {
            get {
                return ResourceManager.GetString("CreateTable_AttributeTypeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_attributevalues
        ///(
        ///    Id INT NOT NULL REFERENCES btz_attribute(Id),
        ///    IdLanguage INT NOT NULL,
        ///    Value VARCHAR(100) NOT NULL,
        ///    PRIMARY KEY 
        ///    (
        ///		Id,
        ///        IdLanguage
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_AttributeValues {
            get {
                return ResourceManager.GetString("CreateTable_AttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_category
        ///(
        ///    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///    IdParent INT REFERENCES btz_category(Id),
        ///    Image VARCHAR(999),
        ///    SKU VARCHAR(256),
        ///    Disabled TINYINT(1) NOT NULL,
        ///    Sort INT(6),
        ///    Highlighted BOOLEAN NOT NULL DEFAULT 0
        ///).
        /// </summary>
        internal static string CreateTable_Category {
            get {
                return ResourceManager.GetString("CreateTable_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_categoryvalue
        ///(
        ///    IdCategory INT NOT NULL REFERENCES btz_category(Id),
        ///    IdLanguage INT NOT NULL,
        ///    Value VARCHAR(100) NOT NULL,
        ///    Info VARCHAR(255)  NULL,
        ///    Url VARCHAR(256),
        ///    PRIMARY KEY 
        ///    (
        ///	        IdCategory,
        ///        IdLanguage
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_CategoryValue {
            get {
                return ResourceManager.GetString("CreateTable_CategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productcombo
        ///(
        ///	IdCombo INT NOT NULL REFERENCES btz_product(Id),
        ///    IdProduct INT NOT NULL REFERENCES btz_product(Id),
        ///    Quantidade INT NOT NULL,
        ///    PRIMARY KEY
        ///    (
        ///        IdCombo,
        ///        IdProduct
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_Combo {
            get {
                return ResourceManager.GetString("CreateTable_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_product
        ///(
        ///    Id INT NOT NULL auto_increment PRIMARY KEY,
        ///    IdType INT,
        ///    SKU VARCHAR(100),
        ///    Sort INT,
        ///    SubProduct INT,
        ///  Disabled TINYINT(1) NOT NULL,
        ///  Hide TINYINT(1) NOT NULL,
        /// FOREIGN KEY (IdType) REFERENCES btz_producttype(Id),
        /// CreatedAt TIMESTAMP NULL DEFAULT NULL,
        /// UpdatedAt TIMESTAMP NULL DEFAULT NULL
        ///).
        /// </summary>
        internal static string CreateTable_Product {
            get {
                return ResourceManager.GetString("CreateTable_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productattribute
        ///(
        ///    IdProduct INT NOT NULL REFERENCES btz_product(Id),
        ///    IdAttribute INT NOT NULL REFERENCES btz_attribute(Id),
        ///    PRIMARY KEY
        ///    (
        ///        IdProduct,
        ///        IdAttribute
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_ProductAttribute {
            get {
                return ResourceManager.GetString("CreateTable_ProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productcategory
        ///(
        ///    IdProduct INT NOT NULL REFERENCES btz_product(Id),
        ///    IdCategory INT NOT NULL REFERENCES btz_category(Id),
        ///    PRIMARY KEY
        ///    (
        ///        IdProduct,
        ///        IdCategory
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_ProductCategory {
            get {
                return ResourceManager.GetString("CreateTable_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productfield
        ///(
        ///    IdField INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///    IdFieldGroup INT NOT NULL REFERENCES btz_productfieldgroup(Id),
        ///    Name VARCHAR(100) NOT NULL,
        ///    Description LONGTEXT,
        ///    Type VARCHAR(100) NOT NULL,
        ///    Format LONGTEXT,
        ///    ReadOnly TINYINT(1) NOT NULL,
        ///    `Order` INT NULL
        ///).
        /// </summary>
        internal static string CreateTable_ProductField {
            get {
                return ResourceManager.GetString("CreateTable_ProductField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productfieldgroup
        ///(
        ///    Id INT NOT NULL auto_increment PRIMARY KEY,
        ///    Description VARCHAR(100)
        ///).
        /// </summary>
        internal static string CreateTable_ProductFieldGroup {
            get {
                return ResourceManager.GetString("CreateTable_ProductFieldGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productfieldtype
        ///(
        ///    IdType int not null references btz_producttype(Id),
        ///    IdField int not null references btz_productfield(IdField),
        ///    PRIMARY KEY
        ///    (
        ///        IdType,
        ///        IdField
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_ProductFieldType {
            get {
                return ResourceManager.GetString("CreateTable_ProductFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productfieldvalue
        ///(
        ///    IdField INT NOT NULL  REFERENCES btz_productfield(IdField),
        ///    IdProduct INT NOT NULL REFERENCES btz_product(Id),
        ///    IdLanguage INT NOT NULL,
        ///    ReadOnly TINYINT(1) NOT NULL,
        ///    Value LONGTEXT,
        ///    PRIMARY KEY (IdField, IdProduct, IdLanguage)
        ///).
        /// </summary>
        internal static string CreateTable_ProductFieldValue {
            get {
                return ResourceManager.GetString("CreateTable_ProductFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productrelated
        ///(
        ///    IdProduct INT NOT NULL REFERENCES btz_product(Id),
        ///    IdRelated INT NOT NULL REFERENCES btz_product(Id),
        ///    PRIMARY KEY
        ///    (
        ///        IdProduct,
        ///        IdRelated
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_ProductReleated {
            get {
                return ResourceManager.GetString("CreateTable_ProductReleated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productsub
        ///(
        ///    IdProduct INT NOT NULL REFERENCES btz_product(Id),
        ///    IdSubProduct INT NOT NULL REFERENCES btz_product(Id),
        ///    PRIMARY KEY
        ///    (
        ///        IdProduct,
        ///        IdSubProduct
        ///    )
        ///).
        /// </summary>
        internal static string CreateTable_ProductSub {
            get {
                return ResourceManager.GetString("CreateTable_ProductSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_producttype
        ///(
        ///    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///    Description varchar(255)
        ///).
        /// </summary>
        internal static string CreateTable_ProductType {
            get {
                return ResourceManager.GetString("CreateTable_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS btz_productuser
        ///(
        ///    IdProduct INT NULL,
        ///    IdUser INT  NULL
        ///).
        /// </summary>
        internal static string CreateTable_ProductUser {
            get {
                return ResourceManager.GetString("CreateTable_ProductUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_attribute WHERE Id = @p0;.
        /// </summary>
        internal static string Delete_Attribute {
            get {
                return ResourceManager.GetString("Delete_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_attributetype WHERE Id = @p0.
        /// </summary>
        internal static string Delete_AttributeType {
            get {
                return ResourceManager.GetString("Delete_AttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_category WHERE Id = @p0.
        /// </summary>
        internal static string Delete_Category {
            get {
                return ResourceManager.GetString("Delete_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productcategory WHERE IdCategory = @p0.
        /// </summary>
        internal static string Delete_CategoryProduct {
            get {
                return ResourceManager.GetString("Delete_CategoryProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productcombo WHERE IdCombo = @p0;.
        /// </summary>
        internal static string Delete_Combo {
            get {
                return ResourceManager.GetString("Delete_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_product WHERE Id = @p0.
        /// </summary>
        internal static string Delete_Product {
            get {
                return ResourceManager.GetString("Delete_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productattribute WHERE IdProduct = @p0.
        /// </summary>
        internal static string Delete_ProductAttribute {
            get {
                return ResourceManager.GetString("Delete_ProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productcategory WHERE IdProduct = @p0.
        /// </summary>
        internal static string Delete_ProductCategory {
            get {
                return ResourceManager.GetString("Delete_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productcombo WHERE IdProduct = @p1 AND IdCombo = @p0.
        /// </summary>
        internal static string Delete_ProductCombo {
            get {
                return ResourceManager.GetString("Delete_ProductCombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productfieldvalue WHERE idProduct = @p0 AND idLanguage = @p1 AND (value IS NULL OR value = &apos;&apos;).
        /// </summary>
        internal static string Delete_ProductFieldValue_NullOrEmpty {
            get {
                return ResourceManager.GetString("Delete_ProductFieldValue_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productrelated WHERE IdProduct = @p0.
        /// </summary>
        internal static string Delete_ProductRelated {
            get {
                return ResourceManager.GetString("Delete_ProductRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productuser WHERE IdProduct = @p0;.
        /// </summary>
        internal static string Delete_ProductUser {
            get {
                return ResourceManager.GetString("Delete_ProductUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productfieldvalue WHERE IdProduct = @p0.
        /// </summary>
        internal static string Delete_ProductValues {
            get {
                return ResourceManager.GetString("Delete_ProductValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM btz_productsub WHERE IdSubProduct = @p0.
        /// </summary>
        internal static string Delete_SubProduct {
            get {
                return ResourceManager.GetString("Delete_SubProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_attribute (IdType, Icon, IdParent) VALUES (@p0, @p1, @p2); SELECT LAST_INSERT_ID().
        /// </summary>
        internal static string Insert_Attribute {
            get {
                return ResourceManager.GetString("Insert_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_attributetype (Codigo) VALUES (&quot;&quot;); SELECT LAST_INSERT_ID().
        /// </summary>
        internal static string Insert_AttributeType {
            get {
                return ResourceManager.GetString("Insert_AttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_attributetypevalues (Id, IdLanguage, Value) VALUES (@p0, @p1, @p2).
        /// </summary>
        internal static string Insert_AttributeTypeValues {
            get {
                return ResourceManager.GetString("Insert_AttributeTypeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_attributevalues (Id, IdLanguage, Value) VALUES (@p0, @p1, @p2).
        /// </summary>
        internal static string Insert_AttributeValues {
            get {
                return ResourceManager.GetString("Insert_AttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_category (IdParent, Image, Disabled, SKU, Sort, Highlighted) VALUES (@p0, @p1, @p2, @p3, @p4, @p5); SELECT LAST_INSERT_ID();.
        /// </summary>
        internal static string Insert_Category {
            get {
                return ResourceManager.GetString("Insert_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_categoryvalue (IdCategory, IdLanguage, Value, Url, Info) VALUES (@p0, @p1, @p2, @p3,@p4).
        /// </summary>
        internal static string Insert_CategoryValue {
            get {
                return ResourceManager.GetString("Insert_CategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productcombo (IdCombo, IdProduct, Quantidade) VALUES (@p0, @p1, 1).
        /// </summary>
        internal static string Insert_Combo {
            get {
                return ResourceManager.GetString("Insert_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_productcombo SET Quantidade = @p0 WHERE IdCombo = @p1 AND IdProduct = @p2.
        /// </summary>
        internal static string Insert_ComboQuantidade {
            get {
                return ResourceManager.GetString("Insert_ComboQuantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_product (SKU,Disabled,Hide,IdType,CreatedAt,UpdatedAt) VALUES (@p0, @p1,@p2,@p3,@p4,@p5); SELECT LAST_INSERT_ID();.
        /// </summary>
        internal static string Insert_Product {
            get {
                return ResourceManager.GetString("Insert_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productattribute (IdProduct, IdAttribute) VALUES (@p0, @p1).
        /// </summary>
        internal static string Insert_ProductAttribute {
            get {
                return ResourceManager.GetString("Insert_ProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productcategory (IdProduct, IdCategory) VALUES (@p0, @p1).
        /// </summary>
        internal static string Insert_ProductCategory {
            get {
                return ResourceManager.GetString("Insert_ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productfieldvalue (IdField, IdProduct, IdLanguage, Value, ReadOnly) 
        ///VALUES (@p0, @p1, @p2, @p3, 0) ON DUPLICATE KEY UPDATE IdProduct=@p1, IdLanguage=@p2, Value = @p3, ReadOnly = 0.
        /// </summary>
        internal static string Insert_ProductFieldValue {
            get {
                return ResourceManager.GetString("Insert_ProductFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productrelated (IdProduct, IdRelated) VALUES (@p0, @p1).
        /// </summary>
        internal static string Insert_ProductRelated {
            get {
                return ResourceManager.GetString("Insert_ProductRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productuser (IdProduct,IdUser) SELECT @p0,@p1 WHERE NOT EXISTS(SELECT * FROM btz_productuser WHERE IdProduct = @p0 AND IdUser = @p1).
        /// </summary>
        internal static string Insert_ProductUser {
            get {
                return ResourceManager.GetString("Insert_ProductUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO btz_productsub (IdProduct, IdSubProduct) VALUES (@p0, @p1).
        /// </summary>
        internal static string Insert_SubProduct {
            get {
                return ResourceManager.GetString("Insert_SubProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	c.*, 
        ///		v.Value AS Description, 
        ///		n.Value as Type,
        ///        b.Codigo
        ///FROM    btz_attribute c
        ///        LEFT JOIN btz_attributevalues v ON c.Id = v.Id AND v.IdLanguage = @p0
        ///		LEFT JOIN btz_attributetype b ON c.IdType = b.Id
        ///		LEFT JOIN btz_attributetypevalues n ON n.Id = c.IdType AND n.IdLanguage = @p0;.
        /// </summary>
        internal static string Select_Attribute {
            get {
                return ResourceManager.GetString("Select_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    c.*, v.Value
        ///FROM
        ///    btz_attributetype c
        ///        LEFT JOIN
        ///    btz_attributetypevalues v ON c.Id = v.Id AND v.IdLanguage = @p0.
        /// </summary>
        internal static string Select_AttributeType {
            get {
                return ResourceManager.GetString("Select_AttributeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM btz_attributevalues WHERE IdLanguage = @p0.
        /// </summary>
        internal static string Select_AttributeValue {
            get {
                return ResourceManager.GetString("Select_AttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.*, v.Value AS Description,v.Info AS Info, v.Url FROM btz_category c LEFT JOIN btz_categoryvalue v ON c.Id = v.IdCategory AND v.IdLanguage = @p0.
        /// </summary>
        internal static string Select_Category {
            get {
                return ResourceManager.GetString("Select_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	Column_Name
        ///FROM information_schema.columns
        ///WHERE TABLE_NAME = &apos;btz_category&apos; AND TABLE_SCHEMA = database().
        /// </summary>
        internal static string Select_Category_Fields {
            get {
                return ResourceManager.GetString("Select_Category_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.*, v.Value AS Description, v.Url FROM btz_category c LEFT JOIN btz_categoryvalue v ON c.Id = v.IdCategory AND v.IdLanguage = @p0 WHERE c.Id = @p1.
        /// </summary>
        internal static string Select_CategoryById {
            get {
                return ResourceManager.GetString("Select_CategoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.*, v.Value AS Description,v.Info AS Info, v.Url FROM btz_category c LEFT JOIN btz_categoryvalue v ON c.Id = v.IdCategory AND v.IdLanguage = @p0.
        /// </summary>
        internal static string Select_CategoryValue {
            get {
                return ResourceManager.GetString("Select_CategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT distinct PC.IdCategory FROM  btz_productcategory AS PC
        ///JOIN btz_product AS P ON PC.IdProduct = P.Id
        ///WHERE P.Disabled = 0 and P.Hide = 0;.
        /// </summary>
        internal static string Select_CategoryWithProductRelated {
            get {
                return ResourceManager.GetString("Select_CategoryWithProductRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  v.IdProduct, f.Name, g.Description AS Category, v.Value, v.IdLanguage, v.ReadOnly, f.Type
        /// FROM   btz_productfieldvalue v
        ///        INNER JOIN btz_productfield f ON v.IdField = f.IdField
        ///        INNER JOIN btz_productfieldgroup g ON f.IdFieldGroup = g.Id
        ///WHERE   v.IdLanguage = @p0.
        /// </summary>
        internal static string Select_Field {
            get {
                return ResourceManager.GetString("Select_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  v.IdProduct, f.Name, g.Description AS Category, v.Value, v.IdLanguage
        ///FROM    btz_productfieldvalue v
        ///        INNER JOIN btz_productfield f ON v.IdField = f.IdField
        ///        INNER JOIN btz_productfieldgroup g ON f.IdFieldGroup = g.Id
        ///WHERE   v.IdLanguage = @p0 AND V.IdProduct = @p1.
        /// </summary>
        internal static string Select_FieldById {
            get {
                return ResourceManager.GetString("Select_FieldById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  v.IdProduct, f.Name, g.Description AS Category, v.Value, v.IdLanguage
        ///FROM    btz_productfieldvalue v
        ///        INNER JOIN btz_productfield f ON v.IdField = f.IdField
        ///        INNER JOIN btz_productfieldgroup g ON f.IdFieldGroup = g.Id
        ///WHERE   v.IdLanguage = @p0 AND IdProduct = @p1.
        /// </summary>
        internal static string Select_FieldByProduct {
            get {
                return ResourceManager.GetString("Select_FieldByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.* FROM btz_product p WHERE p.Id ORDER BY p.Sort, p.Id.
        /// </summary>
        internal static string Select_Product {
            get {
                return ResourceManager.GetString("Select_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Column_Name FROM information_schema.columns WHERE TABLE_NAME = &apos;btz_product&apos; AND TABLE_SCHEMA = database().
        /// </summary>
        internal static string Select_Product_Fields {
            get {
                return ResourceManager.GetString("Select_Product_Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM btz_productattribute;.
        /// </summary>
        internal static string Select_ProductAttribute {
            get {
                return ResourceManager.GetString("Select_ProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.* FROM btz_product p WHERE p.Id = @p0.
        /// </summary>
        internal static string Select_ProductById {
            get {
                return ResourceManager.GetString("Select_ProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.* FROM btz_product p 
        ///INNER JOIN btz_productuser u ON u.IdProduct = p.Id
        ///WHERE p.Id AND u.IdUser = @p0 ORDER BY p.Sort, p.Id.
        /// </summary>
        internal static string Select_ProductByUser {
            get {
                return ResourceManager.GetString("Select_ProductByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    f.*, g.Description AS FieldGroup
        ///FROM
        ///    btz_productfield f
        ///        INNER JOIN
        ///    btz_productfieldgroup g ON f.IdFieldGroup = g.Id
        ///		INNER JOIN
        ///	btz_productfieldtype p ON f.IdField = p.IdField WHERE p.IdType = @p0.
        /// </summary>
        internal static string Select_ProductField {
            get {
                return ResourceManager.GetString("Select_ProductField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    f.*, g.Description AS FieldGroup
        ///FROM
        ///    btz_productfield f
        ///        INNER JOIN
        ///    btz_productfieldgroup g ON f.IdFieldGroup = g.Id.
        /// </summary>
        internal static string Select_ProductField_2 {
            get {
                return ResourceManager.GetString("Select_ProductField_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  v.IdProduct, f.Name, g.Description AS Category, v.Value, v.IdLanguage
        ///FROM    btz_productfieldvalue v
        ///        INNER JOIN btz_productfield f ON v.IdField = f.IdField
        ///        INNER JOIN btz_productfieldgroup g ON f.IdFieldGroup = g.Id
        ///WHERE   v.IdProduct = @p0 AND
        ///		v.IdLanguage = @p1 AND
        ///        v.ReadOnly = 0.
        /// </summary>
        internal static string Select_ProductFieldValue {
            get {
                return ResourceManager.GetString("Select_ProductFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM btz_productfieldvalue.
        /// </summary>
        internal static string Select_ProductFieldValue_2 {
            get {
                return ResourceManager.GetString("Select_ProductFieldValue_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM btz_productfieldvalue WHERE IdLanguage = @p0.
        /// </summary>
        internal static string Select_ProductFieldValueRaw {
            get {
                return ResourceManager.GetString("Select_ProductFieldValueRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id FROM btz_product.
        /// </summary>
        internal static string Select_ProductId {
            get {
                return ResourceManager.GetString("Select_ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT IdRelated FROM btz_productrelated WHERE IdRelated = @p0.
        /// </summary>
        internal static string Select_ProductRelated {
            get {
                return ResourceManager.GetString("Select_ProductRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM btz_producttype.
        /// </summary>
        internal static string Select_ProductType {
            get {
                return ResourceManager.GetString("Select_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM btz_productuser WHERE idProduct = @p0.
        /// </summary>
        internal static string Select_ProductUser {
            get {
                return ResourceManager.GetString("Select_ProductUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.* FROM btz_product p WHERE p.Id IN (SELECT IdSubProduct FROM btz_productsub) ORDER BY p.Sort, p.Id.
        /// </summary>
        internal static string Select_SubProduct {
            get {
                return ResourceManager.GetString("Select_SubProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT p.Id AS IdProduto, u.Id As IdUser, u.FirstName AS UserName FROM btz_productuser AS pu
        ///INNER JOIN btz_user AS u ON pu.IdUser = u.Id
        ///INNER JOIN btz_product AS p ON p.Id = pu.IdProduct
        ///.
        /// </summary>
        internal static string Select_UserByProduct {
            get {
                return ResourceManager.GetString("Select_UserByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_attribute SET IdType = @p1, Icon = @p2, IdParent = @p3 WHERE Id = @p0;.
        /// </summary>
        internal static string Update_Attribute {
            get {
                return ResourceManager.GetString("Update_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_attributetypevalues SET Value = @p2 WHERE Id = @p0 AND IdLanguage = @p1;.
        /// </summary>
        internal static string Update_AttributeTypeValues {
            get {
                return ResourceManager.GetString("Update_AttributeTypeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_attributevalues SET Value = @p2 WHERE Id = @p0 AND IdLanguage = @p1;.
        /// </summary>
        internal static string Update_AttributeValues {
            get {
                return ResourceManager.GetString("Update_AttributeValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_category SET IdParent = @p1, Image = @p2, Disabled = @p3, SKU = @p4, Sort = @p5, Highlighted = @p6 WHERE Id = @p0.
        /// </summary>
        internal static string Update_Category {
            get {
                return ResourceManager.GetString("Update_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_categoryvalue SET Value = @p2, Url = @p3,Info = @p4 WHERE IdCategory = @p0 AND IdLanguage = @p1.
        /// </summary>
        internal static string Update_CategoryValue {
            get {
                return ResourceManager.GetString("Update_CategoryValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_category SET IdParent = NULL WHERE IdParent = @p0.
        /// </summary>
        internal static string Update_ChildrenCategoryNull {
            get {
                return ResourceManager.GetString("Update_ChildrenCategoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_product SET SKU = @p1, Disabled = @p2, Hide = @p3, IdType = @p4, UpdatedAt = @p5 WHERE Id = @p0.
        /// </summary>
        internal static string Update_Product {
            get {
                return ResourceManager.GetString("Update_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_productfieldvalue 
        ///SET    Value = @p3
        ///WHERE  IdField = @p0 AND
        ///       IdProduct = @p1 AND
        ///       IdLanguage = @p2 AND
        ///       ReadOnly = 0.
        /// </summary>
        internal static string Update_ProductFieldValue {
            get {
                return ResourceManager.GetString("Update_ProductFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_productfieldvalue SET Value = @p3 WHERE IdField = @p0 AND IdProduct = @p1 AND IdLanguage = @p2.
        /// </summary>
        internal static string Update_ProductFieldValueRaw {
            get {
                return ResourceManager.GetString("Update_ProductFieldValueRaw", resourceCulture);
            }
        }
    }
}
