//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitzar.CMS.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Setup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Setup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitzar.CMS.Core.Resources.Setup", typeof(Setup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .margin-0{margin:0!important}.margin-3{margin:3px!important}.margin-5{margin:5px!important}.margin-10{margin:10px!important}.margin-15{margin:15px!important}.margin-20{margin:20px!important}.margin-25{margin:25px!important}.margin-30{margin:30px!important}.margin-35{margin:35px!important}.margin-40{margin:40px!important}.margin-45{margin:45px!important}.margin-50{margin:50px!important}.margin-60{margin:60px!important}.margin-70{margin:70px!important}.margin-80{margin:80px!important}.margin-vertical-0{margin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CssShorthands {
            get {
                return ResourceManager.GetString("CssShorthands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///    overflow-x: hidden;
        ///}
        ///
        ///.menu .logo {
        ///    max-width: 100%;
        ///    max-height: 66px
        ///}
        ///
        ///.menu {
        ///    /* Ajustar Cor Menu */
        ///    background-color: gray;
        ///}
        ///
        ///.menu .navigation {
        ///    margin: 0 !important;
        ///}
        ///
        ///.menu .navigation li {
        ///    list-style: none;
        ///    display: inline-block !important;
        ///}
        ///
        ///.menu .navigation li a {
        ///    margin: 23px 0 23px 30px;
        ///    font-weight: bold;
        ///    text-decoration: none;
        ///    text-transform: uppercase;
        ///    display: block;
        ///    color: #396488;
        ///}
        ///
        ///.menu . [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CssStyle {
            get {
                return ResourceManager.GetString("CssStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (function(e){&quot;use strict&quot;;function t(e){return(e||&quot;&quot;).toLowerCase()}var i=&quot;2.1.6&quot;;e.fn.cycle=function(i){var n;return 0!==this.length||e.isReady?this.each(function(){var n,s,o,c,l=e(this),r=e.fn.cycle.log;if(!l.data(&quot;cycle.opts&quot;)){(l.data(&quot;cycle-log&quot;)===!1||i&amp;&amp;i.log===!1||s&amp;&amp;s.log===!1)&amp;&amp;(r=e.noop),r(&quot;--c2 init--&quot;),n=l.data();for(var a in n)n.hasOwnProperty(a)&amp;&amp;/^cycle[A-Z]+/.test(a)&amp;&amp;(c=n[a],o=a.match(/^cycle(.*)/)[1].replace(/^[A-Z]/,t),r(o+&quot;:&quot;,c,&quot;(&quot;+typeof c+&quot;)&quot;),n[o]=c);s=e.extend({},e.fn.cycle.defaults [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsCycle2 {
            get {
                return ResourceManager.GetString("JsCycle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Plugin for Cycle2; Copyright (c) 2012 M. Alsup; v20141007 */ ! function(a) { &quot;use strict&quot;;
        ///    a(document).on(&quot;cycle-bootstrap&quot;, function(a, b, c) { &quot;carousel&quot; === b.fx &amp;&amp; (c.getSlideIndex = function(a) { var b = this.opts()._carouselWrap.children(),
        ///                c = b.index(a); return c % b.length }, c.next = function() { var a = b.reverse ? -1 : 1;
        ///            b.allowWrap === !1 &amp;&amp; b.currSlide + a &gt; b.slideCount - b.carouselVisible || (b.API.advanceSlide(a), b.API.trigger(&quot;cycle-next&quot;, [b]).log(&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsCycle2Carousel {
            get {
                return ResourceManager.GetString("JsCycle2Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Arquivo JS */.
        /// </summary>
        internal static string JsSite {
            get {
                return ResourceManager.GetString("JsSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;pt-br&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;PromoAcao&quot;&gt;
        ///	
        ///	&lt;!-- SEO --&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;&quot;/&gt;
        ///	&lt;meta name=&quot;keywords&quot; content=&quot;&quot;/&gt;
        ///	&lt;meta name=&quot;copyright&quot; content=&quot;@CMS.Configuration.SiteName&quot;/&gt;
        ///	&lt;meta name=&quot;application-name&quot; content=&quot;@CMS.Configuration.SiteName&quot;/&gt;
        ///	
        ///	&lt;meta property=&quot;og:title&quot; content=&quot;@CMS.Configuration.SiteName&quot;/&gt;
        ///	&lt;meta proper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;margin-top-30 margin-bottom-30 text-center&quot;&gt;
        ///    &lt;h1&gt;Home&lt;/h1&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string PageHome {
            get {
                return ResourceManager.GetString("PageHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;margin-top-30 margin-bottom-30 text-center&quot;&gt;
        ///    &lt;h1&gt;404 - Not Found&lt;/h1&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
    }
}
