//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitzar.CMS.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitzar.CMS.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor informado para o Captcha não é válido. Tente novamente..
        /// </summary>
        internal static string Authentication_CaptchaRequired {
            get {
                return ResourceManager.GetString("Authentication_CaptchaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil do usuário padrão não cadastrado no sistema..
        /// </summary>
        internal static string Authentication_DefaultRoleNotProvided {
            get {
                return ResourceManager.GetString("Authentication_DefaultRoleNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login não encontrado para os dados informados..
        /// </summary>
        internal static string Authentication_UserNotFound {
            get {
                return ResourceManager.GetString("Authentication_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache excluído com sucesso..
        /// </summary>
        internal static string Cache_Exclude {
            get {
                return ResourceManager.GetString("Cache_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As configurações para envio de e-mails não foram definidas..
        /// </summary>
        internal static string Configuration_MailServiceNotDefined {
            get {
                return ResourceManager.GetString("Configuration_MailServiceNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados gravados com sucesso!.
        /// </summary>
        internal static string Data_SuccessfullySaved {
            get {
                return ResourceManager.GetString("Data_SuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um texto com o mesmo nome informado já existe..
        /// </summary>
        internal static string Field_TextWithSameNameAlreadyExist {
            get {
                return ResourceManager.GetString("Field_TextWithSameNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos importados com sucesso..
        /// </summary>
        internal static string Import_AllFilesImported {
            get {
                return ResourceManager.GetString("Import_AllFilesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários deletados com sucesso..
        /// </summary>
        internal static string Import_FilesDeleted {
            get {
                return ResourceManager.GetString("Import_FilesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuários inativados com sucesso..
        /// </summary>
        internal static string Import_FilesDisabled {
            get {
                return ResourceManager.GetString("Import_FilesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os arquivos não foram enviados pois são de extensões não autorizadas..
        /// </summary>
        internal static string Library_ExtensionNotAllowed {
            get {
                return ResourceManager.GetString("Library_ExtensionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um arquivo com o mesmo nome informado já existe. Por favor, informe outro valor..
        /// </summary>
        internal static string Library_FileWithSameNameAlreadyExists {
            get {
                return ResourceManager.GetString("Library_FileWithSameNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativação da Conta.
        /// </summary>
        internal static string MailService_ActivateEmailSubject {
            get {
                return ResourceManager.GetString("MailService_ActivateEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redefinição de Senha.
        /// </summary>
        internal static string MailService_ResetPasswordSubject {
            get {
                return ResourceManager.GetString("MailService_ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um ou mais destinatários não estão autorizados a receber notificações..
        /// </summary>
        internal static string MailService_TargetMailNotAllowed {
            get {
                return ResourceManager.GetString("MailService_TargetMailNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail do destinatário não está definido..
        /// </summary>
        internal static string MailService_TargetMailNotDefined {
            get {
                return ResourceManager.GetString("MailService_TargetMailNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O modelo de e-mail solicitado não foi localizado. Modelo: {0}..
        /// </summary>
        internal static string MailService_TemplateNotFound {
            get {
                return ResourceManager.GetString("MailService_TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O template de notificações não foi especificado..
        /// </summary>
        internal static string MailService_TemplateNotificationNotDefined {
            get {
                return ResourceManager.GetString("MailService_TemplateNotificationNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação não permitida. Verifique as suas permissões..
        /// </summary>
        internal static string Membership_ActionNotAllowed {
            get {
                return ResourceManager.GetString("Membership_ActionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os campos devem ser preenchidos..
        /// </summary>
        internal static string Membership_ArgumentNullException {
            get {
                return ResourceManager.GetString("Membership_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário informado já está validado..
        /// </summary>
        internal static string Membership_EmailAlreadyValidated {
            get {
                return ResourceManager.GetString("Membership_EmailAlreadyValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail do usuário ainda não foi validado. Verifique novamente antes de prosseguir..
        /// </summary>
        internal static string Membership_EmailNotValidated {
            get {
                return ResourceManager.GetString("Membership_EmailNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização do e-mail não permitida pois este e-mail informado já existe cadastrado..
        /// </summary>
        internal static string Membership_EmailUpdateNotAllowed {
            get {
                return ResourceManager.GetString("Membership_EmailUpdateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados de acesso informados são inválidos..
        /// </summary>
        internal static string Membership_InvalidCredentials {
            get {
                return ResourceManager.GetString("Membership_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário informado não está cadastrado no sistema..
        /// </summary>
        internal static string Membership_InvalidLoginUser {
            get {
                return ResourceManager.GetString("Membership_InvalidLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação solicitada é inválida..
        /// </summary>
        internal static string Membership_InvalidOperation {
            get {
                return ResourceManager.GetString("Membership_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O token informado para ativação não é válido..
        /// </summary>
        internal static string Membership_InvalidToken {
            get {
                return ResourceManager.GetString("Membership_InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível recuperar a senha do usuário informado, pois esta bloqueado, não existe ou não possui e-mail cadastrado..
        /// </summary>
        internal static string Membership_InvalidUsername {
            get {
                return ResourceManager.GetString("Membership_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Recurso de Membership precisa estar habilitado para utilização da API..
        /// </summary>
        internal static string Membership_MustBeEnabledToUseApi {
            get {
                return ResourceManager.GetString("Membership_MustBeEnabledToUseApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha do usuário deve ser alterada..
        /// </summary>
        internal static string Membership_PasswordMustBeChanged {
            get {
                return ResourceManager.GetString("Membership_PasswordMustBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas informadas não coincidem..
        /// </summary>
        internal static string Membership_PasswordNotMatch {
            get {
                return ResourceManager.GetString("Membership_PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso.
        /// </summary>
        internal static string Membership_PasswordUpdated {
            get {
                return ResourceManager.GetString("Membership_PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha informada é igual a senha atual do seu perfil. Informe uma senha diferente..
        /// </summary>
        internal static string Membership_SamePasswordCannotBeUpdated {
            get {
                return ResourceManager.GetString("Membership_SamePasswordCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações de Login social divergentes..
        /// </summary>
        internal static string Membership_SocialInformationMismatch {
            get {
                return ResourceManager.GetString("Membership_SocialInformationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O provedor de login social informado não existe..
        /// </summary>
        internal static string Membership_SocialProviderNotFound {
            get {
                return ResourceManager.GetString("Membership_SocialProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário já existe cadastrado na plataforma..
        /// </summary>
        internal static string Membership_UserAlreadyExists {
            get {
                return ResourceManager.GetString("Membership_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este usuário não pode acessar o sistema, pois está bloqueado..
        /// </summary>
        internal static string Membership_UserBlocked {
            get {
                return ResourceManager.GetString("Membership_UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome do usuário e senha devem ser informados..
        /// </summary>
        internal static string Membership_UserNameAndPasswordMustBeProvided {
            get {
                return ResourceManager.GetString("Membership_UserNameAndPasswordMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não logado para executar esta ação..
        /// </summary>
        internal static string Membership_UserNotLogged {
            get {
                return ResourceManager.GetString("Membership_UserNotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail de confirmação do cadastro enviado..
        /// </summary>
        internal static string Membership_ValidationEmailSent {
            get {
                return ResourceManager.GetString("Membership_ValidationEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O plugin que você esta subindo está no modo DEBUG. Ative a configuração de DEBUG ou então suba a versão de Release..
        /// </summary>
        internal static string Plugin_DebugLoadError {
            get {
                return ResourceManager.GetString("Plugin_DebugLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin enviado com sucesso..
        /// </summary>
        internal static string Plugin_SuccessfullyUploaded {
            get {
                return ResourceManager.GetString("Plugin_SuccessfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O plugin informado já existe. Se deseja atualizar, remova a versão atual e faça o upload novamente..
        /// </summary>
        internal static string Plugins_AlreadyExists {
            get {
                return ResourceManager.GetString("Plugins_AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O plugin não implementa a interface IPlugin para ser carregado..
        /// </summary>
        internal static string Plugins_NotAllowed {
            get {
                return ResourceManager.GetString("Plugins_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin não encontrado para processar a requisição..
        /// </summary>
        internal static string Plugins_NotFound {
            get {
                return ResourceManager.GetString("Plugins_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao desinstalar plugin. Operação cancelada..
        /// </summary>
        internal static string Plugins_UninstallError {
            get {
                return ResourceManager.GetString("Plugins_UninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos publicados com sucesso!.
        /// </summary>
        internal static string Template_AllFilesPublished {
            get {
                return ResourceManager.GetString("Template_AllFilesPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um ou mais arquivos enviados possuem extensões não permitidas..
        /// </summary>
        internal static string Template_ExtensionNotAllowed {
            get {
                return ResourceManager.GetString("Template_ExtensionNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de arquivo não habilitado para gerenciamento dentro da Plataforma..
        /// </summary>
        internal static string Template_FileTypeNotAllowed {
            get {
                return ResourceManager.GetString("Template_FileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um arquivo válido deve ser enviado..
        /// </summary>
        internal static string Template_MustSendFile {
            get {
                return ResourceManager.GetString("Template_MustSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template solicitado não encontrado na plataforma..
        /// </summary>
        internal static string Template_NotFound {
            get {
                return ResourceManager.GetString("Template_NotFound", resourceCulture);
            }
        }
    }
}
