//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitzar.PagFun.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitzar.PagFun.Helpers.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE 	btz_product
        ///SET 	disabled = 1
        ///where 	SKU = @p0 AND
        ///		Id IN (
        ///			SELECT IdProduct FROM btz_productfieldvalue WHERE IdProduct IN (
        ///				SELECT 	IdSubProduct
        ///				FROM   	btz_productsub
        ///				WHERE  	idProduct = @p1
        ///			)	AND idfield IN (
        ///							SELECT 	IdField 
        ///							FROM 	btz_productfield 
        ///							WHERE 	NAME = &apos;Ingresso de lote?&apos;
        ///				) 
        ///				AND Value = 1
        ///		);
        ///
        ///UPDATE 	btz_product
        ///SET 	disabled = 0
        ///WHERE 	Id = @p2;.
        /// </summary>
        internal static string ActivateLotTicket {
            get {
                return ResourceManager.GetString("ActivateLotTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_userfield uf
        /// SET uf.Value = @p0 
        ///WHERE uf.IdUser = @p1 
        ///AND uf.Name = &apos;SituacaoEstabelecimento&apos;;.
        /// </summary>
        internal static string AlterEstablishmentStatus {
            get {
                return ResourceManager.GetString("AlterEstablishmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_orderdetailfield 
        ///SET Value = CASE WHEN Field = &apos;StatusAtendimento&apos; THEN &apos;Cancelado&apos; ELSE @p1 END
        ///WHERE IdOrderDetail IN
        ///	(
        ///		SELECT	IdOrderDetail
        ///        FROM	btz_orderdetail d
        ///				INNER JOIN btz_order o ON o.Id = d.IdOrder
        ///		WHERE	o.Id = @p0
        ///    )
        ///    AND Field IN (&apos;StatusAtendimento&apos;, &apos;MotivoCancelamento&apos;).
        /// </summary>
        internal static string CancelEstablishmentOrder {
            get {
                return ResourceManager.GetString("CancelEstablishmentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO pagfun_promoter_events(IdPromoter, IdEvent, IdTicket, TicketQuantity, TicketValue, ChargeFee, TicketsTax, Vip)
        ///SELECT	*
        ///FROM	vRemainingPromoters
        ///WHERE	IdEvent = @p0;.
        /// </summary>
        internal static string CreateRemainingPromoterBalance {
            get {
                return ResourceManager.GetString("CreateRemainingPromoterBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS pagfun_extract
        ///(
        ///    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        ///    IdUser INT NOT NULL,
        ///    OperationType VARCHAR(255),
        ///    OperationDetail VARCHAR(255) NOT NULL,
        ///    CreditValue DECIMAL(18,2) NOT NULL,
        ///    CreatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
        ///	UpdatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
        ///    Disabled TINYINT(1) NOT NULL,
        ///    FOREIGN KEY (IdUser) REFERENCES btz_user(Id)
        ///);.
        /// </summary>
        internal static string CreateTableExtract {
            get {
                return ResourceManager.GetString("CreateTableExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	U.Id,
        ///    U.Email,
        ///    U.FirstName,
        ///    U.LastName,
        ///    MAX(CASE WHEN (UF.Name = &apos;Nome Completo&apos;) THEN UF.Value END) AS CompleteName
        ///FROM btz_user U 
        ///JOIN btz_userfield UF 
        ///ON U.Id = UF.IdUser
        ///WHERE U.IdRole = 4 
        ///AND U.Disabled = 0 
        ///AND U.Deleted = 0
        ///AND (U.Email LIKE @p0 OR U.FirstName LIKE @p0 OR U.LastName LIKE @p0)
        ///GROUP BY U.Id, U.Email;.
        /// </summary>
        internal static string GerUsersByEmailAndName {
            get {
                return ResourceManager.GetString("GerUsersByEmailAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM vAdminEventBalance WHERE EventId = @p0.
        /// </summary>
        internal static string GetAdminTicketsBalanceByEvent {
            get {
                return ResourceManager.GetString("GetAdminTicketsBalanceByEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT po.Id as EventId,
        ///       po.SKU,
        ///       po.EventName,
        ///       po.EventLocal,
        ///       po.EventImageId,
        ///       po.EventInicialDate,
        ///       po.EventFinalDate,
        ///       po.CityId,  
        ///       AV.Value as City,
        ///  po.Disabled,
        ///  po.Hide
        ///  FROM (
        ///    SELECT
        ///    P.Id,
        ///    P.SKU,
        ///    PFV.IdProduct AS IdProduct,
        ///    P.Hide,
        ///    P.Disabled,
        ///    P.IdType,
        ///    MAX(PAT.IdAttribute) AS CityId,
        ///    MAX(CASE WHEN (PF.Name = &apos;Description&apos;) THEN PFV.Value END) AS EventName,
        ///    MAX(CASE WHEN (PF.Name = &apos;N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllActiveEvents {
            get {
                return ResourceManager.GetString("GetAllActiveEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 	R.Id AS EventId,
        ///		MAX(CASE WHEN (F.Name = &apos;Description&apos;) THEN P.Value END) AS EventName,
        ///		MAX(CASE WHEN (F.Name = &apos;Nome local&apos;) THEN P.Value END) AS EventLocal,
        ///		MAX(CASE WHEN (F.Name = &apos;Mini banner&apos;) THEN P.Value END) AS EventImageId,
        ///		MAX(CASE WHEN (F.Name = &apos;Data de inicio&apos;) THEN P.Value END) AS EventInicialDate,
        ///		MAX(CASE WHEN (F.Name = &apos;Data de término&apos;) THEN P.Value END) AS EventFinalDate,
        ///		MAX(CASE WHEN (F.Name = &apos;Data de término&apos;) THEN P.Value END) AS EventFinalDate,
        ///		PAT.IdAtt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllEvents {
            get {
                return ResourceManager.GetString("GetAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 	R.Id AS EventId,
        ///		MAX(CASE WHEN (F.Name = &apos;Description&apos;) THEN P.Value END) AS EventName,
        ///		MAX(CASE WHEN (F.Name = &apos;Nome local&apos;) THEN P.Value END) AS EventLocal,
        ///		MAX(CASE WHEN (F.Name = &apos;Mini banner&apos;) THEN P.Value END) AS EventImageId,
        ///		MAX(CASE WHEN (F.Name = &apos;Data de inicio&apos;) THEN P.Value END) AS EventInicialDate,
        ///		MAX(CASE WHEN (F.Name = &apos;Data de término&apos;) THEN P.Value END) AS EventFinalDate,
        ///		MAX(CASE WHEN (F.Name = &apos;Data de término&apos;) THEN P.Value END) AS EventFinalDate,
        ///		PAT.IdAtt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllEventsActive {
            get {
                return ResourceManager.GetString("GetAllEventsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  po.EventId, 
        ///		po.EventName, 
        ///		po.SKU,
        ///		po.EventLocal,
        ///		po.EventImageId,
        ///		po.EventInicialDate,
        ///		po.EventFinalDate,
        ///		po.CityId, 
        ///		City,
        ///		Status,
        ///		SUM(Quantity) as Quantity
        ///FROM 	vorderdetailfield ODF
        ///		INNER JOIN vproductevent po ON ODF.EventId = po.EventId
        ///WHERE 	po.EventInicialDate &gt;= CURRENT_DATE AND Status = 3 AND Price &gt; 0
        ///GROUP 	BY po.EventId, po.EventName, po.SKU, po.EventLocal, po.EventImageId, po.EventInicialDate, po.EventFinalDate, po.CityId, City, Status
        ///ORDER 	BY 6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetBestSellersEvents {
            get {
                return ResourceManager.GetString("GetBestSellersEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 	
        ///        pu.IdUser AS IdEstabelecimento,
        ///        o.id AS NrPedido,
        ///        date(SUBSTRING(o.DataPedido,1,10)) AS DataPedido,
        ///        SUBSTRING(o.DataPedido,12,5) AS HoraPedido,
        ///        pftp.Value as DescricaoProduto,
        ///		    ca.value AS Categoria,
        ///	    	o.Price as Preco,
        ///        o.Quantity as Quant,
        ///        CONCAT( u.FirstName, &apos; &apos;, u.Lastname ) AS Cliente,
        ///        o.Mesa,
        ///        o.StatusAtendimento,
        ///        SUBSTRING(o.DataAtendimento,12,5) AS HoraAtendimento,
        ///        o.TempoEntrega,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEstablishmentOrders {
            get {
                return ResourceManager.GetString("GetEstablishmentOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 	pev.Value as EventName,
        ///		P.SKU as Sku,
        ///		pftp.Value as ProductName,
        ///		ca.value AS Category,
        ///		o.Price as Price,
        ///        o.Quantity as Quantity,
        ///        t.OwnerName as BuyerName,
        ///        u.Email as BuyerEmail,
        ///        t.DataConsumo as ConsumeDate,     
        ///        t.Status as Status,
        ///        usu.UserName as UserReadQR ,
        ///        t.CreationDate as BuyDate,
        ///        o.IdTicket
        ///FROM	(
        ///			SELECT  o.Id,
        ///					d.IdProduct AS IdSeq,
        ///					d.Quantity,
        ///					d.Price,
        ///                    o.Status,
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEventProductsSold {
            get {
                return ResourceManager.GetString("GetEventProductsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	po.EventId,
        ///		po.NomeIngresso,
        ///		po.ValorIngresso,
        ///		po.DataInicio
        ///FROM (
        ///		SELECT	ps.IdProduct AS EventId,
        ///				CAST(MAX(CASE WHEN (PF.Name = &apos;Valor do ingresso&apos;) THEN PFV.Value END) AS DECIMAL) AS ValorIngresso,
        ///				MAX(CASE WHEN (PF.Name = &apos;Descrição do ingresso&apos;) THEN PFV.Value END) AS NomeIngresso,
        ///				CAST(MAX(CASE WHEN (PF.Name = &apos;Data e hora de inicio&apos;) THEN PFV.Value END) AS DATETIME) AS DataInicio
        ///		FROM 	btz_productsub ps
        ///				INNER JOIN btz_product P ON P.id = ps.idsubproduct            /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEventTickets {
            get {
                return ResourceManager.GetString("GetEventTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM pagfun_extract WHERE IdUser = @p0;.
        /// </summary>
        internal static string GetExtractByUser {
            get {
                return ResourceManager.GetString("GetExtractByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT po.Id as EventId,
        ///       po.SKU,
        ///       po.EventName,
        ///       po.EventLocal,
        ///       po.EventImageId,
        ///       po.EventInicialDate,
        ///       po.EventFinalDate,
        ///       po.CityId,  
        ///       AV.Value as City,
        ///  po.Disabled,
        ///  po.Hide
        ///  FROM (
        ///    SELECT
        ///    P.Id,
        ///    P.SKU,
        ///    PFV.IdProduct AS IdProduct,
        ///    P.Hide,
        ///    P.Disabled,
        ///    P.IdType,
        ///    MAX(PAT.IdAttribute) AS CityId,
        ///    MAX(CASE WHEN (PF.Name = &apos;Description&apos;) THEN PFV.Value END) AS EventName,
        ///    MAX(CASE WHEN (PF.Name = &apos;N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetNextEvents {
            get {
                return ResourceManager.GetString("GetNextEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 	O.Id,
        ///		O.IdCustomer,
        ///		CAST((OD.Price) AS DECIMAL(12,2)) AS Price,
        ///		CAST((MAX(CASE WHEN (OF.Field = &apos;Credit&apos;) THEN OF.Value END)) AS DECIMAL(12,2)) AS Credit,
        ///		MAX(CASE WHEN (ODF.Field = &apos;EventName&apos;) THEN ODF.Value END) AS OrderName,
        ///        MAX(CASE WHEN (ODF.Field = &apos;OwnerName&apos;) THEN ODF.Value END) AS OwnerName
        ///FROM btz_order O
        ///JOIN btz_orderfield OF 
        ///ON O.Id = OF.IdOrder
        ///JOIN btz_orderdetail OD
        ///ON O.Id = OD.IdOrder
        ///JOIN btz_orderdetailfield ODF
        ///ON OD.Id = ODF.IdOrderDetail
        ///WHERE O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOrderById {
            get {
                return ResourceManager.GetString("GetOrderById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 	O.Id,
        ///		O.Uuid,
        ///		O.IdCustomer ,
        ///		CAST(SUM(OD.Price) AS DECIMAL(12,2)) AS Price,
        ///		MAX(CAST(OF.Value AS DECIMAL(12,2))) AS Credit,
        ///		PFV.Value AS EventName
        ///FROM btz_order O
        ///JOIN btz_orderfield OF 
        /// 	ON O.Id = OF.IdOrder AND OF.Field = &apos;Credit&apos;
        ///JOIN btz_orderdetail OD
        ///	ON O.Id = OD.IdOrder
        ///JOIN btz_orderdetailfield ODF
        ///	ON OD.Id = ODF.IdOrderDetail AND ODF.Field = &apos;IdEvent&apos;
        ///JOIN btz_product PD
        ///	ON	ODF.Value = PD.Id
        ///JOIN btz_productfieldvalue PFV
        ///	ON	PD.Id = PFV.IdProduct
        ///JOIN btz_pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOrderByUuid {
            get {
                return ResourceManager.GetString("GetOrderByUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM pagfun_promoter_invite WHERE IdUser = @p0;.
        /// </summary>
        internal static string GetPromoterInvitesByIdUser {
            get {
                return ResourceManager.GetString("GetPromoterInvitesByIdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM vPromoterEventBalance WHERE PromoterCode = @p0 AND SectionId = @p1.
        /// </summary>
        internal static string GetPromoterTicketBalanceByPromoterCode {
            get {
                return ResourceManager.GetString("GetPromoterTicketBalanceByPromoterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM pagfun_promoter_events WHERE IdPromoter = @p0 AND IdTicket = @p1;.
        /// </summary>
        internal static string GetPromoterTicketByPromoterCode {
            get {
                return ResourceManager.GetString("GetPromoterTicketByPromoterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	e.*
        ///FROM	pagfun_promoter_events e
        ///		INNER JOIN btz_userfield f
        ///			ON	f.Name = &apos;CodigoPromoter&apos; AND
        ///				e.IdPromoter = f.Value
        ///		INNER JOIN btz_user u
        ///			ON	f.IdUser = u.Id
        ///WHERE	u.Email = @p0 AND e.IdEvent = @p1 AND e.IdTicket = @p2.
        /// </summary>
        internal static string GetPromoterTicketValue {
            get {
                return ResourceManager.GetString("GetPromoterTicketValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM btz_ticket 
        ///where Id = @p0;.
        /// </summary>
        internal static string GetTicketById {
            get {
                return ResourceManager.GetString("GetTicketById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	U.Id,
        ///    U.Email,
        ///    U.FirstName,
        ///    U.LastName,
        ///	MAX(CASE WHEN (UF.Name = &apos;Nome Completo&apos;) THEN UF.Value END) AS CompleteName
        ///FROM btz_user U
        ///JOIN btz_userfield UF
        ///ON U.Id = UF.IdUser
        ///WHERE U.Email = @p0 
        ///GROUP BY U.Id, U.Email;.
        /// </summary>
        internal static string GetUserByEmail {
            get {
                return ResourceManager.GetString("GetUserByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///FROM btz_user 
        ///where Id = @p0;.
        /// </summary>
        internal static string GetUserById {
            get {
                return ResourceManager.GetString("GetUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id FROM btz_userfield where btz_userfield.Name = &apos;CPF&apos; AND Value = @p0 LIMIT 1;.
        /// </summary>
        internal static string GetUserCPF {
            get {
                return ResourceManager.GetString("GetUserCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO pagfun_promoter_events(IdPromoter, IdEvent, IdTicket, TicketQuantity, TicketValue, ChargeFee, TicketsTax, Vip) VALUES(@p0,@p1,@p2,@p3,@p4,@p5,@p6,@p7);.
        /// </summary>
        internal static string InsertPromoterEvent {
            get {
                return ResourceManager.GetString("InsertPromoterEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO pagfun_promoter_invite(IdPromoter, IdUser, IdEvent, PromoterName, PromoterEmail, Status, CreatedAt, UpdatedAt) VALUES(@p0,null,@p1,@p2,@p3, &apos;Pendente&apos;, @p4, @p5);.
        /// </summary>
        internal static string InsertPromoterInvite {
            get {
                return ResourceManager.GetString("InsertPromoterInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM pagfun_promoter_invite WHERE IdEvent = @p0;.
        /// </summary>
        internal static string ListPromotersInviteByEvent {
            get {
                return ResourceManager.GetString("ListPromotersInviteByEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T.IdEvent as IdEvent,
        ///	COUNT(T.IdEvent) as Solds
        ///	FROM btz_ticket T
        ///	WHERE T.Type = @p0 AND T.Status = @p1
        ///	GROUP BY T.IdEvent
        ///	ORDER BY Solds DESC;.
        /// </summary>
        internal static string RetrieveEventSolds {
            get {
                return ResourceManager.GetString("RetrieveEventSolds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUM(
        ///CASE WHEN T.Status = 0
        ///THEN 1 ELSE 0 END) AS Created,
        ///SUM(
        ///CASE WHEN T.Status = 1
        ///THEN 1 ELSE 0 END) AS Emitted,
        ///SUM(
        ///CASE WHEN T.Status = 3
        ///THEN 1 ELSE 0 END) AS Cancelled,
        ///T.IdEvent as IdEvent,
        ///COUNT(T.IdEvent) as Solds
        ///FROM btz_ticket T
        ///WHERE T.Type = &apos;Event&apos; AND T.AlterationDate &gt;= @p0 AND T.AlterationDate &lt;= @p1
        ///GROUP BY T.IdEvent;.
        /// </summary>
        internal static string RetrieveTicketsBySituation_New {
            get {
                return ResourceManager.GetString("RetrieveTicketsBySituation_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUM(
        ///CASE WHEN T.Status = 0
        ///THEN 1 ELSE 0 END) AS Created,
        ///SUM(
        ///CASE WHEN T.Status = 1
        ///THEN 1 ELSE 0 END) AS Emitted,
        ///SUM(
        ///CASE WHEN T.Status = 3
        ///THEN 1 ELSE 0 END) AS Cancelled,
        ///T.IdEvent as IdEvent,
        ///COUNT(T.IdEvent) as Solds
        ///FROM btz_ticket T
        ///WHERE T.Type = &apos;Event&apos;
        ///GROUP BY T.IdEvent
        ///ORDER BY Solds DESC;.
        /// </summary>
        internal static string RetrieveTicketsBySituation_Old {
            get {
                return ResourceManager.GetString("RetrieveTicketsBySituation_Old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T.IdEvent as IdEvent,
        ///	T.IdSection as IdSection,
        ///	COUNT(T.IdEvent) as Solds
        ///	FROM btz_ticket T
        ///	WHERE T.AlterationDate &gt;= @p0 AND T.AlterationDate &lt;= @p1
        ///    AND T.Type = @p2 AND T.Status = @p3
        ///	GROUP BY T.IdEvent, T.IdSection
        ///	ORDER BY Solds DESC;.
        /// </summary>
        internal static string RetrieveTicketsCount {
            get {
                return ResourceManager.GetString("RetrieveTicketsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	P.Id,
        ///    PC.IdCategory,
        ///	P.Disabled
        ///FROM btz_productcategory PC
        ///INNER JOIN btz_product P ON P.Id = PC.IdProduct
        ///WHERE PC.IdCategory = @p0.
        /// </summary>
        internal static string RetriveAllEventsByCategory {
            get {
                return ResourceManager.GetString("RetriveAllEventsByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  T.IdEvent as Event,
        ///COUNT(T.IdEvent) as Solds
        /// FROM btz_ticket T 
        ///WHERE T.Type = &apos;Event&apos; AND T.Status = 0 OR T.Status = 1 OR T.Status = 5 
        ///GROUP BY T.IdEvent 
        ///ORDER BY Solds DESC;.
        /// </summary>
        internal static string RetriveBestSellers {
            get {
                return ResourceManager.GetString("RetriveBestSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T.IdEvent as Event,
        ///COUNT(T.IdEvent) as Solds,
        ///cv.Value AS Category,
        ///cv.IdCategory AS IdCategory,
        ///c.Disabled AS CategoryDisabled,
        ///c.Highlighted AS CategoryHighlighted
        ///FROM btz_ticket T
        ///INNER JOIN btz_productcategory pc ON pc.IdProduct = T.IdEvent
        ///INNER JOIN btz_category c ON c.Id = pc.IdCategory
        ///INNER JOIN btz_categoryvalue cv ON cv.IdCategory = pc.IdCategory
        ///WHERE T.Type = &apos;Event&apos; AND cv.IdCategory = @p0 AND T.Status != 2 AND T.Status != 3 AND T.Status != 4
        ///GROUP BY T.IdEvent, cv.Value, c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetriveBestSellersCategory {
            get {
                return ResourceManager.GetString("RetriveBestSellersCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	C.Id AS IdCategory,
        ///	C.IdParent,
        ///    C.Disabled,
        ///    C.Highlighted,
        ///    C.Image AS ImageDefault,
        ///    CV.Value AS CategoryName,
        ///    CV.Url AS CategoryUrl
        ///FROM btz_category C
        ///INNER JOIN btz_categoryvalue CV ON CV.IdCategory = C.Id
        ///WHERE C.IdParent = @p0 AND C.Disabled = 0;.
        /// </summary>
        internal static string RetriveCategoriesByIdParent {
            get {
                return ResourceManager.GetString("RetriveCategoriesByIdParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT IdUser FROM btz_ticket WHERE IdSection = @p0;.
        /// </summary>
        internal static string RetriveDistinctUserFromSection {
            get {
                return ResourceManager.GetString("RetriveDistinctUserFromSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT R.IdProduct as EventId
        ///FROM btz_productsub R
        ///WHERE R.IdSubProduct = @p0;.
        /// </summary>
        internal static string RetriveEventIdFromSectionId {
            get {
                return ResourceManager.GetString("RetriveEventIdFromSectionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT R.Id as EventId,
        ///    MAX(CASE WHEN (F.Name = &apos;Description&apos;) THEN P.Value END) AS EventName,
        ///    MAX(CASE WHEN (F.Name = &apos;Nome local&apos;) THEN P.Value END) AS EventLocal,
        ///    MAX(CASE WHEN (F.Name = &apos;Mini banner&apos;) THEN P.Value END) AS EventImageId,
        ///	MAX(CASE WHEN (F.Name = &apos;Data de inicio&apos;) THEN P.Value END) AS EventInicialDate,
        ///	MAX(CASE WHEN (F.Name = &apos;Data de término&apos;) THEN P.Value END) AS EventFinalDate,
        ///MAX(CASE WHEN (F.Name = &apos;Preço do produto&apos;) THEN P.Value END) AS PriceProduct
        ///FRO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetriveFormatedEvent {
            get {
                return ResourceManager.GetString("RetriveFormatedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT R.Id as EventId,
        ///    MAX(CASE WHEN (F.Name = &apos;Description&apos;) THEN P.Value END) AS EventName,
        ///    MAX(CASE WHEN (F.Name = &apos;Nome local&apos;) THEN P.Value END) AS EventLocal,
        ///    MAX(CASE WHEN (F.Name = &apos;Mini banner&apos;) THEN P.Value END) AS EventImageId,
        ///    MAX(CASE WHEN (F.Name = &apos;Data de término&apos;) THEN P.Value END) AS EventFinalDate
        ///FROM btz_product R
        ///INNER JOIN btz_productfieldvalue P ON P.IdProduct = R.Id
        ///INNER JOIN btz_productfield F ON F.IdField = P.IdField
        ///WHERE R.Disabled = 0 AND R.Id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetriveFormatedEventBestSellers {
            get {
                return ResourceManager.GetString("RetriveFormatedEventBestSellers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT R.Id as SectionId,
        ///    MAX(CASE WHEN (F.Name = &apos;Description&apos;) THEN P.Value END) AS SectionName,
        ///    MAX(CASE WHEN (F.Name = &apos;Data e hora de inicio&apos;) THEN P.Value END) AS SectionDateTime,
        ///    MAX(CASE WHEN (F.Name = &apos;Taxa de serviços&apos;) THEN P.Value END) AS SectionTicketTax,
        ///	MAX(CASE WHEN (F.Name = &apos;Valor do ingresso&apos;) THEN P.Value END) AS SectionTicketValue
        ///FROM btz_product R
        ///INNER JOIN btz_productfieldvalue P ON P.IdProduct = R.Id
        ///INNER JOIN btz_productfield F ON F.IdField = P.IdFiel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetriveFormatedSection {
            get {
                return ResourceManager.GetString("RetriveFormatedSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT sections.Id FROM (
        ///	SELECT DISTINCT 
        ///	R.Id as Id, 
        ///    CASE WHEN (F.Name = &apos;Description&apos;) THEN P.Value END AS SectionName,
        ///	STR_TO_DATE (CASE WHEN(F.Name = &apos;Data e hora de inicio&apos;) THEN P.Value END,&apos;%Y-%m-%dT%H:%i&apos;) AS SectionDateTime
        ///	FROM btz_product R
        ///	INNER JOIN btz_productfieldvalue P ON P.IdProduct = R.Id
        ///	INNER JOIN btz_productfield F ON F.IdField = P.IdField
        ///	WHERE R.IdType = 2 AND F.Name = &apos;Data e hora de inicio&apos;
        ///	GROUP BY R.Id, P.Value
        ///	) sections
        ///WHERE DAY(CURDATE()) = DAY(DATE_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RetriveSectionsBeforeXDays {
            get {
                return ResourceManager.GetString("RetriveSectionsBeforeXDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT	c.*, 
        ///		v.Value AS Description, 
        ///		n.Value as Type,
        ///        b.Codigo
        ///FROM    btz_attribute c
        ///        LEFT JOIN btz_attributevalues v ON c.Id = v.Id AND v.IdLanguage = @p0
        ///		LEFT JOIN btz_attributetype b ON c.IdType = b.Id
        ///		LEFT JOIN btz_attributetypevalues n ON n.Id = c.IdType AND n.IdLanguage = @p0;.
        /// </summary>
        internal static string SelectAttributes {
            get {
                return ResourceManager.GetString("SelectAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_ticket TK
        ///SET TK.OwnerName = @p1, TK.IdUser = @p2
        ///WHERE TK.Id = @p0;.
        /// </summary>
        internal static string SetNewOwnerTicket {
            get {
                return ResourceManager.GetString("SetNewOwnerTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_order
        ///SET btz_order.Status = 3
        ///WHERE btz_order.Id = @p0;.
        /// </summary>
        internal static string UpdateOrderStatusApproved {
            get {
                return ResourceManager.GetString("UpdateOrderStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_order
        ///SET btz_order.Status = 3
        ///WHERE btz_order.Uuid= @p0;.
        /// </summary>
        internal static string UpdateOrderStatusApprovedUuid {
            get {
                return ResourceManager.GetString("UpdateOrderStatusApprovedUuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_product
        /// SET Hide = false,
        /// Disabled = false
        /// WHERE Id = @p0;.
        /// </summary>
        internal static string UpdateProductStatusToActive {
            get {
                return ResourceManager.GetString("UpdateProductStatusToActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_product
        /// SET Hide = false,
        /// Disabled = true
        ///WHERE Id = @p0;.
        /// </summary>
        internal static string UpdateProductStatusToDisabled {
            get {
                return ResourceManager.GetString("UpdateProductStatusToDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_product
        /// SET Hide = true
        ///WHERE Id = @p0;.
        /// </summary>
        internal static string UpdateProductStatusToPaused {
            get {
                return ResourceManager.GetString("UpdateProductStatusToPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pagfun_promoter_events SET TicketQuantity = @p1, TicketValue = @p2, ChargeFee = @p3, TicketsTax = @p4, vip = @p5 WHERE Id = @p0;.
        /// </summary>
        internal static string UpdatePromoterEvents {
            get {
                return ResourceManager.GetString("UpdatePromoterEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE	btz_productfieldvalue
        ///SET		Value = CASE
        ///					WHEN IdField = (SELECT IdField FROM btz_productfield f WHERE IdField = btz_productfieldvalue.IdField AND Name = &apos;Data e hora de inicio&apos;) THEN @p2
        ///                    WHEN IdField = (SELECT IdField FROM btz_productfield f WHERE IdField = btz_productfieldvalue.IdField AND Name = &apos;Data de inicio das vendas&apos;) THEN @p3
        ///                    WHEN IdField = (SELECT IdField FROM btz_productfield f WHERE IdField = btz_productfieldvalue.IdField AND Name = &apos;Data de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateSessionDates {
            get {
                return ResourceManager.GetString("UpdateSessionDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE pagfun_promoter_invite SET pagfun_promoter_invite.Status = &apos;Aprovado&apos;, IdUser = @p0, UpdatedAt = now() WHERE pagfun_promoter_invite.IdPromoter = @p1;.
        /// </summary>
        internal static string UpdateStatusPromoterInvite {
            get {
                return ResourceManager.GetString("UpdateStatusPromoterInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE btz_user SET IdRole = 8 WHERE btz_user.Id = @p0;.
        /// </summary>
        internal static string UpdateUserRolePromoter {
            get {
                return ResourceManager.GetString("UpdateUserRolePromoter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM pagfun_promoter_invite WHERE IdUser = @p0 AND IdEvent = @p1;.
        /// </summary>
        internal static string ValidateIfPromoterInviteExists {
            get {
                return ResourceManager.GetString("ValidateIfPromoterInviteExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW `vproductevent` AS select `po`.`Id` AS `EventId`,`po`.`SKU` AS `SKU`,`po`.`EventName` AS `EventName`,`po`.`EventLocal` AS `EventLocal`,`po`.`EventImageId` AS `EventImageId`,`po`.`EventInicialDate` AS `EventInicialDate`,`po`.`EventFinalDate` AS `EventFinalDate`,`po`.`CityId` AS `CityId`,`av`.`Value` AS `City`,`po`.`Disabled` AS `Disabled`,`po`.`Hide` AS `Hide` from (((select `p`.`Id` AS `Id`,`p`.`SKU` AS `SKU`,`pfv`.`IdProduct` AS `IdProduct`,`p`.`Hide` AS `Hide`,`p`.`Disabled` AS `Dis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewAdminEventBalance {
            get {
                return ResourceManager.GetString("ViewAdminEventBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW vorderdetailfield
        ///AS
        ///SELECT  o.Id,
        ///	d.IdProduct AS IdSeq,
        ///	d.Quantity,
        ///	d.Price,
        ///	o.Status,
        ///	MAX(IF(f.Field = &apos;IdSection&apos;, f.Value, NULL)) AS IdSection,
        ///	MAX(IF(f.Field = &apos;IdEvent&apos;, f.Value, NULL)) AS EventId,
        ///	MAX(IF(f.Field = &apos;IdTicket&apos;, f.Value, NULL)) AS IdTicket,
        ///	MAX(IF(f.Field = &apos;StatusEntrega&apos;, f.Value, NULL)) AS ItemOrderStatus,
        ///	MAX(IF(f.Field = &apos;Mesa&apos;, f.Value, NULL)) AS Mesa,
        ///	MAX(IF(f.Field = &apos;DataEntrega&apos;, f.Value, NULL)) AS DataEntrega,
        ///	MAX(IF(f.Field = &apos;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewOrderDetailField {
            get {
                return ResourceManager.GetString("ViewOrderDetailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW vproductevent
        ///AS 
        ///SELECT po.Id AS EventId,
        ///       po.SKU,
        ///       po.EventName,
        ///       po.EventLocal,
        ///       po.EventImageId,
        ///       po.EventInicialDate,
        ///       po.EventFinalDate,
        ///       po.CityId,
        ///       AV.Value as City,
        ///  po.Disabled,
        ///  po.Hide
        ///  FROM (
        ///    SELECT
        ///    P.Id,
        ///    P.SKU,
        ///    PFV.IdProduct AS IdProduct,
        ///    P.Hide,
        ///    P.Disabled,
        ///    P.IdType,
        ///    MAX(PAT.IdAttribute) AS CityId,
        ///    MAX(CASE WHEN (PF.Name = &apos;Description&apos;) THEN PFV.Value END) AS Ev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewProductEvent {
            get {
                return ResourceManager.GetString("ViewProductEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW `vproducteventdetail` AS select `pd`.`Id` AS `IdEvent`,`pdfd`.`Value` AS `EventName`,`subpd`.`Id` AS `IdSection`,`sdfd`.`Value` AS `SectionName`,cast(`pdfv`.`Value` as signed) AS `TicketFullStorage`,cast(replace(replace(`pdfvl`.`Value`,&apos;.&apos;,&apos;&apos;),&apos;,&apos;,&apos;.&apos;) as decimal(18,2)) AS `TicketFullValue`,(coalesce(`promoterevents`.`FullReservedStock`,0) - coalesce(`tickets`.`PromotersSoldTickets`,0)) AS `ReservedStock`,coalesce(`tickets`.`SoldTickets`,0) AS `SoldTickets`,coalesce(`tickets`.`DirectS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewProductEventDetail {
            get {
                return ResourceManager.GetString("ViewProductEventDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW `vpromotereventbalance` AS select `products`.`IdEvent` AS `EventId`,`products`.`EventName` AS `EventName`,`products`.`IdSection` AS `SectionId`,`products`.`SectionName` AS `SectionName`,`promoterevents`.`IdPromoter` AS `PromoterCode`,`products`.`TicketFullValue` AS `FullValue`,max(`promoterevents`.`TicketValue`) AS `PromoterValue`,count(distinct `tickets`.`IdOrder`) AS `Orders`,`products`.`TicketFullStorage` AS `Storage`,`products`.`SoldTickets` AS `SoldTickets`,((max(`products`.`Tick [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewPromoterEventBalance {
            get {
                return ResourceManager.GetString("ViewPromoterEventBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW `vremainingpromoters` AS select `uf`.`Value` AS `IdPromoter`,`event`.`IdEvent` AS `IdEvent`,`event`.`IdSection` AS `IdTicket`,0 AS `TicketQuantity`,`event`.`TicketFullValue` AS `TicketValue`,0 AS `ChargeFee`,0 AS `TicketsTax`,0 AS `Vip` from (((`vproducteventdetail` `event` join `btz_user` `user`) join `btz_userfield` `uf` on(((`user`.`Id` = `uf`.`IdUser`) and (`uf`.`Name` = &apos;CodigoPromoter&apos;)))) left join `pagfun_promoter_events` `pe` on(((`event`.`IdEvent` = `pe`.`IdEvent`) and (`eve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewRemainingPromoters {
            get {
                return ResourceManager.GetString("ViewRemainingPromoters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE OR REPLACE VIEW `vsoldticketsbyorder` AS select `ordervalue`.`IdOrder` AS `IdOrder`,`ticketvalue`.`uuidOrder` AS `uuidOrder`,`ticketvalue`.`IdEvent` AS `IdEvent`,`ticketvalue`.`IdSection` AS `IdSection`,`ordervalue`.`PromoterEmail` AS `PromoterEmail`,(case when ((`ordervalue`.`PromoterCode` is not null) and (`ordervalue`.`PromoterCode` &lt;&gt; &apos;&apos;)) then `ordervalue`.`PromoterCode` else NULL end) AS `PromoterCode`,`ticketvalue`.`SoldTickets` AS `SoldTickets`,max(`ordervalue`.`Price`) AS `Price` from (((sel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ViewSoldTicketsByOrder {
            get {
                return ResourceManager.GetString("ViewSoldTicketsByOrder", resourceCulture);
            }
        }
    }
}
